language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - build-tools-26.0.2
    - android-26
    - android-15

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
